# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e8bb80314ce5744a45751f5bbfc41a59a035d1cf35621b1075b9a11e36bf9125fe1af16a5b8dd354ae849242a1da671efcc9df1c08de9c408fc825fd365c36c

test:
  secret_key_base: c718a31c4b1e0676753c75394374fb17324b583650df4ed82883924c4da6ba49ec835d5e8111d8e6531f2fdc65c9058d2e6edc1f86a4eb721dbf136fcb2f717b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
